import fs from 'node:fs/promises';
const FORMATS=new Set(['single_image','static','carousel','reel']);
const TEMPLATES=new Set(['template_insight_light','template_announcement_dark','template_carousel_cover','template_offer_card']);
const PROVENANCE=['asset_id','provider','photographer','source_page','license_name','license_url','verified_at','usage_scope'];
const req=(v,n)=>{if(typeof v!=='string'||!v.trim())throw new Error(`${n} is required.`)};
function fields(f,c){if(!f||typeof f!=='object'||Array.isArray(f))throw new Error(`${c}.fields must be an object.`);req(f['field.category'],`${c}.fields[field.category]`);req(f['field.headline'],`${c}.fields[field.headline]`);req(f['field.media'],`${c}.fields[field.media]`);if(String(f['field.headline']).length>90)throw new Error(`${c} headline exceeds 90 characters.`);if(String(f['field.body']||'').length>280)throw new Error(`${c} body exceeds 280 characters.`)}
function provenance(p,c){if(!p||typeof p!=='object'||Array.isArray(p))throw new Error(`${c}.media_provenance is required.`);for(const k of PROVENANCE)req(p[k],`${c}.media_provenance.${k}`);if(!String(p.source_page).startsWith('https://')||!String(p.license_url).startsWith('https://'))throw new Error(`${c} provenance URLs must use HTTPS.`);if(Number.isNaN(Date.parse(p.verified_at)))throw new Error(`${c}.media_provenance.verified_at must be a valid date.`)}
export function validateManifest(m){if(!m||typeof m!=='object'||Array.isArray(m))throw new Error('Manifest must be an object.');const format=String(m.format||m.render_type||'').toLowerCase();if(!FORMATS.has(format))throw new Error(`Unsupported format: ${format||'(missing)'}`);req(m.post_code,'post_code');req(m.schema_version,'schema_version');req(m.template_id,'template_id');if(!TEMPLATES.has(m.template_id))throw new Error(`Unsupported template_id: ${m.template_id}`);if(m.publishing_allowed!==false)throw new Error('publishing_allowed must be false for internal preview renders.');const w=Number(m.canvas?.width||m.width),h=Number(m.canvas?.height||m.height),eh=format==='reel'?1920:1080;if(w!==1080||h!==eh)throw new Error(`Canvas must be exactly 1080x${eh}.`);if(format==='carousel'){if(!Array.isArray(m.slides)||m.slides.length<2)throw new Error('Carousel requires at least two slides.');const media=[];m.slides.forEach((s,i)=>{if(!TEMPLATES.has(s.template_id||m.template_id))throw new Error(`slides[${i}] template is unsupported.`);fields(s.fields,`slides[${i}]`);provenance(s.media_provenance,`slides[${i}]`);media.push(String(s.fields['field.media']).trim())});if(new Set(media).size!==media.length)throw new Error('Carousel media sources must be distinct.');if(m.media_policy?.distinct_media_per_slide!==true||m.media_policy?.provenance_required!==true)throw new Error('Carousel media policy is incomplete.');}else if(format==='reel'){if(!Array.isArray(m.scenes)||m.scenes.length<2)throw new Error('Reel requires at least two scenes.');if(m.audio?.enabled!==false||m.voiceover?.enabled!==false)throw new Error('Silent dry-run Reel requires audio and voiceover disabled.');const media=[];let total=0;m.scenes.forEach((s,i)=>{if(!TEMPLATES.has(s.template_id||m.template_id))throw new Error(`scenes[${i}] template is unsupported.`);fields(s.fields,`scenes[${i}]`);provenance(s.media_provenance,`scenes[${i}]`);const d=Number(s.duration_seconds);if(!Number.isFinite(d)||d<=0||d>10)throw new Error(`scenes[${i}] duration_seconds is invalid.`);total+=d;media.push(String(s.fields['field.media']).trim())});if(total<18||total>22)throw new Error('Reel total duration must be between 18 and 22 seconds.');if(new Set(media).size!==media.length)throw new Error('Reel media sources must be distinct.');if(m.media_policy?.distinct_media_per_scene!==true||m.media_policy?.provenance_required!==true)throw new Error('Reel media policy is incomplete.');}else fields(m.fields,'manifest');return true}
export async function readManifest(file){let m;try{m=JSON.parse(await fs.readFile(file,'utf8'))}catch(e){throw new Error(`Invalid JSON: ${e.message}`)}validateManifest(m);return m}
export function formatOf(m){const v=String(m.format||m.render_type).toLowerCase();return v==='static'?'single_image':v}
