import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { readManifest, formatOf } from './manifest.mjs';
const arg=(n,f)=>{const i=process.argv.indexOf(n);return i<0?f:process.argv[i+1]};
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');
const wrap=(t,max=30,limit=3)=>{const w=String(t||'').trim().split(/\s+/).filter(Boolean),a=[];let l='';for(const x of w){const n=l?`${l} ${x}`:x;if(n.length<=max||!l)l=n;else{a.push(l);l=x;if(a.length>=limit-1)break}}if(l&&a.length<limit)a.push(l);return a};
const themes={template_insight_light:{bg:'#F3F7FA',panel:'#FFF',headline:'#071B33',body:'#10253E',accent:'#0D5EA6',eyebrow:'#0D5EA6',footer:'#5F7185'},template_announcement_dark:{bg:'#071B33',panel:'#0B2E52',headline:'#FFF',body:'#8FE3F1',accent:'#28B8D8',eyebrow:'#8FE3F1',footer:'#A8BED0'},template_carousel_cover:{bg:'#0D5EA6',panel:'#0D5EA6',headline:'#FFF',body:'#D7EEF5',accent:'#B8D82E',eyebrow:'#FFF',footer:'#D7EEF5'},template_offer_card:{bg:'#F3F7FA',panel:'#FFF',headline:'#071B33',body:'#5F7185',accent:'#B8D82E',eyebrow:'#0D5EA6',footer:'#5F7185'}};
async function media(url,w,h){if(!url)return null;const u=new URL(url);if(u.protocol!=='https:'||u.hostname!=='images.unsplash.com')throw new Error('Media URL is not allowlisted.');const r=await fetch(u,{headers:{'User-Agent':'GDSBEDS-internal-renderer/1.0'}});if(!r.ok)throw new Error(`Media download failed: ${r.status}`);const b=Buffer.from(await r.arrayBuffer());if(b.length>15000000)throw new Error('Media exceeds 15 MB.');const o=await sharp(b).rotate().resize({width:w,height:h,fit:'cover',position:'attention'}).jpeg({quality:84}).toBuffer();return `data:image/jpeg;base64,${o.toString('base64')}`}
async function svg({width,height,templateId,fields,index,total}){const t=themes[templateId]||themes.template_insight_light,m=Math.round(width*.065),x=m+55,w=width-m*2-110,hy=Math.round(height*.15),hh=Math.round(height*(height>1200?.46:.31)),img=await media(String(fields['field.media']||'').trim(),w,hh),h=String(fields['field.headline']||'').trim(),b=String(fields['field.body']||'').trim(),cat=String(fields['field.category']||'GDS BEDS').trim().toUpperCase(),hl=wrap(h,25,height>1200?4:3),bl=wrap(b,42,3),hs=Math.round(width*(height>1200?.075:.058)),bs=Math.round(width*.028),ty=hy+hh+95,by=height-m;return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="100%" height="100%" fill="${t.bg}"/><rect x="${m}" y="${m}" width="${width-m*2}" height="${height-m*2}" rx="28" fill="${t.panel}"/><text x="${x}" y="${m+78}" font-family="Arial" font-size="24" font-weight="700" fill="${t.eyebrow}" letter-spacing="2">${esc(cat)}</text>${img?`<image x="${x}" y="${hy}" width="${w}" height="${hh}" href="${img}" preserveAspectRatio="xMidYMid slice"/>`:''}${hl.map((l,i)=>`<text x="${x}" y="${ty+i*hs*1.1}" font-family="Arial" font-size="${hs}" font-weight="700" fill="${t.headline}">${esc(l)}</text>`).join('')}${bl.map((l,i)=>`<text x="${x}" y="${ty+hl.length*hs*1.1+55+i*bs*1.4}" font-family="Arial" font-size="${bs}" fill="${t.body}">${esc(l)}</text>`).join('')}<text x="${x}" y="${by}" font-family="Arial" font-size="28" font-weight="700" fill="${t.headline}" letter-spacing="3">GDS BEDS</text><text x="${width-m-55}" y="${by}" text-anchor="end" font-family="Arial" font-size="18" fill="${t.footer}">INTERNAL PREVIEW • NOT FOR PUBLISHING</text>${total>1?`<text x="${width-m-55}" y="${m+78}" text-anchor="end" font-family="Arial" font-size="22" font-weight="700" fill="${t.eyebrow}">${index}/${total}</text>`:''}</svg>`}
const manifestPath=arg('--manifest',process.env.MANIFEST_PATH||'manifest.json'),out=path.resolve(arg('--output',process.env.OUTPUT_DIR||'dist')),manifest=await readManifest(manifestPath),format=formatOf(manifest),canvas=manifest.canvas||{},width=Number(canvas.width||manifest.width),height=Number(canvas.height||manifest.height);await fs.rm(out,{recursive:true,force:true});await fs.mkdir(out,{recursive:true});const entries=format==='carousel'?manifest.slides.map((s,i)=>({templateId:s.template_id||manifest.template_id,fields:s.fields,suffix:`slide-${String(i+1).padStart(2,'0')}`,duration:0})):format==='reel'?manifest.scenes.map((s,i)=>({templateId:s.template_id||manifest.template_id,fields:s.fields,suffix:`scene-${String(i+1).padStart(2,'0')}`,duration:Number(s.duration_seconds||3)})):[{templateId:manifest.template_id,fields:manifest.fields,suffix:'preview',duration:0}],files=[],sources=[];for(let i=0;i<entries.length;i++){const e=entries[i],src=String(e.fields['field.media']||'').trim();if(src)sources.push(src);const n=`${manifest.post_code}-${e.suffix}.svg`;await fs.writeFile(path.join(out,n),await svg({width,height,...e,index:i+1,total:entries.length}),'utf8');files.push(n)}const result={ok:true,render_id:process.env.RENDER_ID||manifest.render_id||`RND-${manifest.post_code}`,post_code:manifest.post_code,format,template_id:manifest.template_id,schema_version:manifest.schema_version,generated_at:new Date().toISOString(),files,scene_durations:entries.map(e=>e.duration),media_embedded:sources.length===entries.length,media_sources:[...new Set(sources)],publication_ready:false};await fs.writeFile(path.join(out,'result.json'),`${JSON.stringify(result,null,2)}\n`,'utf8');console.log(JSON.stringify(result));