import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { readManifest, formatOf } from './manifest.mjs';
const arg=(n,f)=>{const i=process.argv.indexOf(n);return i<0?f:process.argv[i+1]};
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');
function wrap(t,max=30,limit=3){const w=String(t||'').trim().split(/\s+/).filter(Boolean),a=[];let l='';for(const x of w){const n=l?`${l} ${x}`:x;if(n.length<=max||!l)l=n;else{a.push(l);l=x;if(a.length>=limit-1)break}}if(l&&a.length<limit)a.push(l);return a}
const txt=(a,x,y,s,step,w=700,c='#fff')=>a.map((l,i)=>`<text x="${x}" y="${y+i*step}" font-family="Arial,Helvetica,sans-serif" font-size="${s}" font-weight="${w}" fill="${c}">${esc(l)}</text>`).join('');
const themes={template_insight_light:{bg:'#F3F7FA',panel:'#FFF',headline:'#071B33',body:'#10253E',accent:'#0D5EA6',eyebrow:'#0D5EA6',footer:'#5F7185'},template_announcement_dark:{bg:'#071B33',panel:'#0B2E52',headline:'#FFF',body:'#8FE3F1',accent:'#28B8D8',eyebrow:'#8FE3F1',footer:'#A8BED0'},template_carousel_cover:{bg:'#0D5EA6',panel:'#0D5EA6',headline:'#FFF',body:'#D7EEF5',accent:'#B8D82E',eyebrow:'#FFF',footer:'#D7EEF5'},template_offer_card:{bg:'#F3F7FA',panel:'#FFF',headline:'#071B33',body:'#5F7185',accent:'#B8D82E',eyebrow:'#0D5EA6',footer:'#5F7185'}};
async function media(url,w,h){if(!url)return null;const u=new URL(url);if(u.protocol!=='https:'||u.hostname!=='images.unsplash.com')throw new Error('Media URL is not allowlisted.');const r=await fetch(u,{headers:{'User-Agent':'GDSBEDS-internal-renderer/1.0'}});if(!r.ok)throw new Error(`Media download failed: ${r.status}`);const b=Buffer.from(await r.arrayBuffer());if(b.length>15000000)throw new Error('Media exceeds 15 MB.');const o=await sharp(b).rotate().resize({width:w,height:h,fit:'cover',position:'attention'}).jpeg({quality:84}).toBuffer();return `data:image/jpeg;base64,${o.toString('base64')}`}
async function svg({width,height,templateId,fields,index,total}){const t=themes[templateId]||themes.template_insight_light,m=Math.round(width*.065),x=m+78,w=width-m*2-156,hy=Math.round(height*.16),hh=Math.round(height*.31),img=await media(String(fields['field.media']||'').trim(),w,hh),h=String(fields['field.headline']||'').trim(),b=String(fields['field.body']||'').trim(),cat=String(fields['field.category']||'GDS BEDS').trim().toUpperCase(),dest=String(fields['field.destination']||'').trim(),hotel=String(fields['field.hotel_name']||'').trim(),meta=String(fields['field.offer_meta']||'').trim(),price=String(fields['field.price']||'').trim(),hl=wrap(hotel||h,27,3),bl=wrap(meta||b,47,3),hs=Math.round(width*.058),bs=Math.round(width*.026),ty=Math.round(height*.57),by=height-m,clip=`hero-${index}`;return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><defs><clipPath id="${clip}"><rect x="${x}" y="${hy}" width="${w}" height="${hh}" rx="22"/></clipPath></defs><rect width="100%" height="100%" fill="${t.bg}"/><rect x="${m}" y="${m}" width="${width-m*2}" height="${height-m*2}" rx="28" fill="${t.panel}"/><rect x="${m+38}" y="${m+42}" width="12" height="${height-m*2-84}" rx="6" fill="${t.accent}"/><text x="${x}" y="${m+78}" font-family="Arial" font-size="${Math.round(width*.021)}" font-weight="700" fill="${t.eyebrow}" letter-spacing="2">${esc(dest||cat)}</text>${img?`<image x="${x}" y="${hy}" width="${w}" height="${hh}" href="${img}" preserveAspectRatio="xMidYMid slice" clip-path="url(#${clip})"/><rect x="${x}" y="${hy}" width="${w}" height="${hh}" rx="22" fill="none" stroke="${t.accent}" stroke-width="3"/>`:`<rect x="${x}" y="${hy}" width="${w}" height="${hh}" rx="22" fill="#071B33"/>`}${txt(hl,x,ty,hs,Math.round(hs*1.08),700,t.headline)}${txt(bl,x,ty+hl.length*Math.round(hs*1.08)+34,bs,Math.round(bs*1.4),400,t.body)}${price?`<text x="${x}" y="${height-m-92}" font-family="Arial" font-size="${Math.round(width*.052)}" font-weight="700" fill="#0D5EA6">${esc(price)}</text>`:''}<text x="${x}" y="${by}" font-family="Arial" font-size="${Math.round(width*.026)}" font-weight="700" fill="${t.headline}" letter-spacing="3">GDS BEDS</text><text x="${width-m-78}" y="${by}" text-anchor="end" font-family="Arial" font-size="${Math.round(width*.018)}" fill="${t.footer}">INTERNAL PREVIEW • NOT FOR PUBLISHING</text>${total>1?`<text x="${width-m-78}" y="${m+78}" text-anchor="end" font-family="Arial" font-size="${Math.round(width*.022)}" font-weight="700" fill="${t.eyebrow}">${index}/${total}</text>`:''}</svg>`}
const manifestPath=arg('--manifest',process.env.MANIFEST_PATH||'manifest.json'),out=path.resolve(arg('--output',process.env.OUTPUT_DIR||'dist')),manifest=await readManifest(manifestPath),format=formatOf(manifest),canvas=manifest.canvas||{},width=Number(canvas.width||manifest.width),height=Number(canvas.height||manifest.height);await fs.rm(out,{recursive:true,force:true});await fs.mkdir(out,{recursive:true});const entries=format==='carousel'?manifest.slides.map((s,i)=>({templateId:s.template_id||manifest.template_id,fields:s.fields||manifest.fields||{},suffix:`slide-${String(i+1).padStart(2,'0')}`})):[{templateId:manifest.template_id,fields:manifest.fields||{},suffix:'preview'}],files=[],sources=[];for(let i=0;i<entries.length;i++){const e=entries[i],src=String(e.fields['field.media']||'').trim();if(src)sources.push(src);const n=`${manifest.post_code}-${e.suffix}.svg`;await fs.writeFile(path.join(out,n),await svg({width,height,...e,index:i+1,total:entries.length}),'utf8');files.push(n)}const result={ok:true,render_id:process.env.RENDER_ID||manifest.render_id||`RND-${manifest.post_code}`,post_code:manifest.post_code,format,template_id:manifest.template_id,schema_version:manifest.schema_version,generated_at:new Date().toISOString(),files,media_embedded:sources.length===entries.length,media_sources:[...new Set(sources)],publication_ready:false};await fs.writeFile(path.join(out,'result.json'),`${JSON.stringify(result,null,2)}\n`,'utf8');console.log(JSON.stringify(result));
